version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-southeast-2:274201610284:task-definition/authorization-service:1"
        LoadBalancerInfo:
          ContainerName: "authorization-service"
          ContainerPort: "8081"
# Optional properties
        PlatformVersion: "LATEST"
